import katex from "katex";
import { DOMParser, type Node as XmlNode, type Element as XmlElement } from "@xmldom/xmldom";
import { Math as WordMath, MathRun, MathFraction, MathSubScript, MathSuperScript, MathSubSuperScript, MathRadical, MathLimitLower, MathLimitUpper, type MathComponent } from "docx";
import { BuilderElement, createMathAccentCharacter } from "docx";

// Convert the MathML generated by the same renderer as the UI into editable
// Word equations. Keep unsupported structures as readable Unicode, never HTML.
export function wordEquation(tex: string): WordMath {
  const xml = katex.renderToString(tex, { output: "mathml", throwOnError: true, strict: false });
  const document = new DOMParser().parseFromString(xml, "text/xml");
  function convert(node?: XmlNode): MathComponent[] {
    if (!node) return [];
    if (node.nodeType === 3) return node.nodeValue?.trim() ? [new MathRun(node.nodeValue)] : [];
    const name = node.nodeName;
    if (name === "annotation") return [];
    const elements = Array.from(node.childNodes).filter(n => n.nodeType === 1);
    const child = (index: number) => convert(elements[index]);
    if (["mi", "mn", "mo", "mtext"].includes(name)) return [new MathRun(node.textContent ?? "")];
    if (name === "mfrac") return [new MathFraction({ numerator: child(0), denominator: child(1) })];
    if (name === "msub") return [new MathSubScript({ children: child(0), subScript: child(1) })];
    if (name === "msup") return [new MathSuperScript({ children: child(0), superScript: child(1) })];
    if (name === "msubsup") return [new MathSubSuperScript({ children: child(0), subScript: child(1), superScript: child(2) })];
    if (name === "msqrt") return [new MathRadical({ children: elements.flatMap(convert) })];
    if (name === "mroot") return [new MathRadical({ children: child(0), degree: child(1) })];
    if (name === "munder") return [new MathLimitLower({ children: child(0), limit: child(1) })];
    if (name === "mover" && (node as XmlElement).getAttribute("accent") === "true") return [new BuilderElement({ name: "m:acc", children: [new BuilderElement({ name: "m:accPr", children: [createMathAccentCharacter({ accent: elements[1]?.textContent ?? "ˆ" })] }), new BuilderElement({ name: "m:e", children: child(0) })] })];
    if (name === "mover") return [new MathLimitUpper({ children: child(0), limit: child(1) })];
    if (name === "munderover") return [new MathLimitUpper({ children: [new MathLimitLower({ children: child(0), limit: child(1) })], limit: child(2) })];
    if (name === "mtable") return [new BuilderElement({ name: "m:m", children: elements.map(row => new BuilderElement({ name: "m:mr", children: Array.from(row.childNodes).filter(n => n.nodeType === 1).map(cell => new BuilderElement({ name: "m:e", children: convert(cell) })) })) })];
    return Array.from(node.childNodes).flatMap(convert);
  }
  return new WordMath({ children: convert(document.documentElement ?? undefined) });
}
